---
- name: Install nginx package
  apt:
    name: nginx
    state: latest
  notify: nginx systemd

- name: Replace nginx.conf
  template:
    src=/etc/ansible/roles/nginx/templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Create home directory for www
  file:
    path: /var/www/{{ virtual_domain }}
    state: directory

- name: Add virtual domain in NGINX for Deb
  vars:
    fastcgi_pass_path: /run/php/php7.2-fpm.sock
  template:
    src=templates/nginx_vhosts.conf
    dest=/etc/nginx/sites-enabled/{{ virtual_domain }}.conf
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx restart
