---
- hosts: db

  vars_files:
    - /root/.ansible/vars/wordpress_vault.yml
    - /root/.ansible/roles/wordpress/vars/wordpress.yml
  roles:
    - /etc/ansible/roles/nginx
    - geerlingguy.php
    - geerlingguy.mysql
    - wordpress
