---
- hosts: db

  vars_files:
    - /root/.ansible/vars/wordpress.yml
    - /root/.ansible/vars/wordpress_vault.yml
    - /root/.ansible/roles/wordpress/vars/wordpress.yml
  roles:
    - { role: /etc/ansible/roles/nginx, tags: [nginx] }
    - { role: geerlingguy.php, tags: [php] }
    - { role: geerlingguy.mysql, tags: [mysql] }
    - { role: wordpress, tags: [wordpress] }
